name: Add VPS Provider
description: Submit a new VPS provider with BGP support
title: "[Add]: "
labels: ["new-provider"]
assignees:
  - Bitti09
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a VPS provider! Please fill out the information below.

  - type: input
    id: provider-name
    attributes:
      label: Provider Name
      description: The name of the VPS provider
      placeholder: "Example: Test VPS"
    validations:
      required: true

  - type: input
    id: asn
    attributes:
      label: ASN
      description: "The provider's Autonomous System Number (numbers only, without 'AS' prefix). Example: Enter '12345' not 'AS12345'"
      placeholder: "12345"
    validations:
      required: true

  - type: dropdown
    id: table-type
    attributes:
      label: BGP Table Type
      description: What type of BGP table does the provider offer?
      multiple: false
      options:
        - Full Table
        - Half Table
      default: 0
    validations:
      required: true

  - type: dropdown
    id: rpki-status
    attributes:
      label: RPKI Filtering
      description: Does the provider offer RPKI filtering?
      multiple: false
      options:
        - "Yes"
        - "No"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: prefix-status
    attributes:
      label: Prefix Update Status
      description: The provider's prefix update status
      multiple: false
      options:
        - Automatic
        - Manual
      default: 0
    validations:
      required: true

  - type: dropdown
    id: loa-required
    attributes:
      label: LOA Required
      description: Does the provider require a Letter of Authorization?
      multiple: false
      options:
        - "Yes"
        - "No"
      default: 1
    validations:
      required: true

  - type: input
    id: locations
    attributes:
      label: Locations
      description: List the locations in "City, CC" format (comma-separated)
      placeholder: "Amsterdam, NL; New York, US; Hong Kong, HK; London, GB"
    validations:
      required: true

  - type: input
    id: services
    attributes:
      label: Services
      description: List the services offered (comma-separated)
      placeholder: "VPS, Dedicated Servers"
    validations:
      required: true

  - type: input
    id: features
    attributes:
      label: BGP Features
      description: List the BGP-related features (comma-separated)
      placeholder: "BGP Community Passthrough, Downstream Support"
    validations:
      required: true

  - type: input
    id: bgp-fee
    attributes:
      label: BGP Setup Fee
      description: The setup fee for BGP (numbers only, enter 0 if there is no fee)
      placeholder: "10"
    validations:
      required: true

  - type: input
    id: pricing
    attributes:
      label: Monthly Pricing
      description: The starting monthly price (numbers only)
      placeholder: "4"
    validations:
      required: true

  - type: dropdown
    id: currency
    attributes:
      label: Currency
      description: The currency for pricing
      multiple: false
      options:
        - USD
        - EUR
        - GBP
        - CHF
        - SEK
        - CZK
      default: 0
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Additional notes about the provider's BGP offering (optional)
      placeholder: "Special features, network access, or other relevant information..."
    validations:
      required: false

  - type: input
    id: url
    attributes:
      label: Provider URL
      description: The website URL of the provider
      placeholder: "https://example.com"
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any additional information about the provider (optional)
      placeholder: "Additional details about the provider's BGP offering..."
    validations:
      required: false

  - type: checkboxes
    id: agreements
    attributes:
      label: Agreements & Verification
      description: Please confirm the following before submitting
      options:
        - label: I agree that bgp.mom can use the provider's logo on the website
          required: true
        - label: I have verified all information is accurate and the provider actively supports BGP
          required: true
        - label: I understand this submission will be reviewed and must comply with our policy
          required: true