blank_issues_enabled: false
contact_links:
  - name: BGP.mom Website
    url: https://bgp.mom
    about: Visit our main website to browse BGP providers
  - name: Documentation
    url: https://github.com/Bitti09/bgp.mom/blob/main/README.md
    about: Read the project documentation and contributing guidelines
